"""add chapter_paths to clips

Revision ID: 31bd52c385c9
Revises: 8aef12bb24d9
Create Date: 2026-06-06 16:49:18.909149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31bd52c385c9'
down_revision: Union[str, Sequence[str], None] = '8aef12bb24d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('chapter_paths', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clips', 'chapter_paths')
    # ### end Alembic commands ###
