"""initial schema

Revision ID: 8aef12bb24d9
Revises: 
Create Date: 2026-06-06 16:41:32.790336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aef12bb24d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('color_grade', sa.String(), nullable=False),
    sa.Column('music_energy', sa.String(), nullable=False),
    sa.Column('target_duration_youtube_s', sa.Integer(), nullable=True),
    sa.Column('target_duration_short_s', sa.Integer(), nullable=True),
    sa.Column('min_clip_s', sa.Float(), nullable=True),
    sa.Column('max_clip_s', sa.Float(), nullable=True),
    sa.Column('overlay_speed', sa.Boolean(), nullable=False),
    sa.Column('overlay_altitude', sa.Boolean(), nullable=False),
    sa.Column('overlay_gps_map', sa.Boolean(), nullable=False),
    sa.Column('speed_threshold_kmh', sa.Float(), nullable=True),
    sa.Column('motion_threshold', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('camera', sa.String(), nullable=True),
    sa.Column('total_clips', sa.Integer(), nullable=True),
    sa.Column('total_duration_s', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('proxy_path', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('codec', sa.String(), nullable=True),
    sa.Column('has_telemetry', sa.Boolean(), nullable=False),
    sa.Column('peak_speed_kmh', sa.Float(), nullable=True),
    sa.Column('peak_altitude_m', sa.Float(), nullable=True),
    sa.Column('peak_motion', sa.Float(), nullable=True),
    sa.Column('scene_count', sa.Integer(), nullable=True),
    sa.Column('clip_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=False),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('aspect', sa.String(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clip_id', sa.String(), nullable=False),
    sa.Column('in_s', sa.Float(), nullable=False),
    sa.Column('out_s', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('order_in_edit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clip_id', sa.String(), nullable=False),
    sa.Column('timestamp_s', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('accel_magnitude', sa.Float(), nullable=True),
    sa.Column('motion_intensity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry')
    op.drop_table('marks')
    op.drop_table('exports')
    op.drop_table('clips')
    op.drop_table('sessions')
    op.drop_table('profiles')
    # ### end Alembic commands ###
